package app.univtool.core;

import java.nio.file.Files;
import java.nio.file.Path;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Objects;
import java.util.UUID;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;

public class ReminderStore {
    public enum Priority { HOLIDAY, EXAM, WARNING_HIGH, WARNING_MED, WARNING_LOW, CUSTOM }
    public static class Reminder {
        public String id;            // UUID
        public String dateIso;       // yyyy-MM-dd
        public Integer courseId;     // null可
        public Integer nth;          // null可
        public String title;         // 表示用
        public String detail;        // クリック詳細
        public String colorHex;      // "#RRGGBB" or null
        public Priority priority = Priority.CUSTOM;
        public boolean autoGenerated = false; // 警告生成フラグ
        
        // ToDoとの連携
        public String linkedTodoId;  // リマインダーに対応するToDoのID（無ければnull）
        public String origin;        // "TODO","CUSTOM","AUTO" など
    }
    public static class Data { public List<Reminder> list = new ArrayList<>(); }

    private static final Gson G = new GsonBuilder().setPrettyPrinting().create();
    private static final String FILE = "reminders.json";
    private static ReminderStore INSTANCE;
    private Data data;

    private ReminderStore(Data d) { this.data = (d == null ? new Data() : d); }
    public static synchronized ReminderStore get() {
        if (INSTANCE == null) INSTANCE = new ReminderStore(load());
        return INSTANCE;
    }

    public synchronized Reminder add(Reminder r) {
        if (r.id == null) r.id = UUID.randomUUID().toString();
        data.list.add(r); save(); return r;
    }
    public synchronized void remove(String id) {
        data.list.removeIf(x -> Objects.equals(x.id, id)); save();
    }
    public synchronized List<Reminder> on(LocalDate d) {
        String iso = d.toString();
        List<Reminder> out = new ArrayList<>();
        for (Reminder r : data.list) if (Objects.equals(r.dateIso, iso)) out.add(r);
        out.sort(Comparator.comparing((Reminder r)->r.priority.ordinal()));
        return out;
    }
    public synchronized List<Reminder> byCourse(Integer cid) {
        List<Reminder> out = new ArrayList<>();
        for (Reminder r : data.list) if (Objects.equals(r.courseId, cid)) out.add(r);
        out.sort(Comparator.comparing((Reminder r)->r.dateIso));
        return out;
    }
    public synchronized void save() { save(data); }

    private static Data load() {
        try { Path p = AppPaths.appHome().resolve(FILE);
              if (Files.exists(p)) return G.fromJson(Files.readString(p), Data.class);
        } catch (Exception ignore) {}
        return new Data();
    }
    private static void save(Data d) {
        try {
            Files.createDirectories(AppPaths.appHome());
            Files.writeString(AppPaths.appHome().resolve(FILE), G.toJson(d));
        } catch (Exception ignore) {}
    }
    public synchronized void remove(Reminder r) {
        if (r != null && r.id != null) remove(r.id);
    }
    
    public synchronized List<Reminder> listAll() {
        return new ArrayList<>(data.list);
    }
    public synchronized Reminder find(String id) {
        for (var r : data.list) if (Objects.equals(r.id, id)) return r;
        return null;
    }

}
