package app.univtool.core;

import java.nio.file.Files;
import java.nio.file.Path;
import java.time.LocalDate;
import java.util.Objects;
import java.util.stream.Collectors;

import app.univtool.core.ReminderStore.Priority;
import app.univtool.core.ReminderStore.Reminder;
import app.univtool.core.TodoStore.TodoItem;
import app.univtool.files.SavedFileIndex;
import app.univtool.model.Course;
import app.univtool.repo.CourseRepository;
import app.univtool.ui.panel2.FileSaveOps;

public class TodoReminderLinker {

    private static final CourseRepository courseRepo = new CourseRepository();

    // === 公開API ===
    /** ToDoの追加 */
    public static synchronized TodoItem addAndLink(TodoItem t) {
        TodoStore.get().add(t);
        ensureLinkedReminder(t);
        return t;
    }

    /** ToDoの更新 */
    public static synchronized void updateAndLink(TodoItem t) {
        TodoStore.get().update(t);
        ensureLinkedReminder(t);
    }

    /** ToDoの削除 */
    public static synchronized void removeWithReminder(TodoItem t) {
        if (t == null) return;
        if (t.linkedReminderId != null) {
            ReminderStore.get().remove(t.linkedReminderId);
            t.linkedReminderId = null;
        }
        TodoStore.get().remove(t.id);
    }

    /** リマインダー編集の反映 */
    public static synchronized void onReminderEdited(Reminder r) {
        if (r == null || r.linkedTodoId == null) return;

        // アーカイブ講義に紐づくリマインダーは無効
        if (isArchivedCourseId(r.courseId)) {
            ReminderStore.get().remove(r.id);
            return;
        }

        var opt = TodoStore.get().find(r.linkedTodoId);
        if (opt.isEmpty()) return;
        var t = opt.get();

        t.dueIso  = r.dateIso;
        t.title   = r.title;
        t.detail  = r.detail;

        TodoStore.get().update(t);
    }

    /** リマインダー削除の反映 */
    public static synchronized void onReminderDeleted(Reminder r) {
        if (r == null) return;

        // 直接リンクされている ToDo を更新
        if (r.linkedTodoId != null) {
            var opt = TodoStore.get().find(r.linkedTodoId);
            if (opt.isPresent()) {
                var t = opt.get();
                if (Objects.equals(t.linkedReminderId, r.id)) {
                    t.linkedReminderId = null;
                }
                t.dueIso = null;
                t.done   = true;
                TodoStore.get().update(t);
            }
        }

        // 全ToDoを走査してリマインダーID参照を掃除
        if (r.id != null) {
            for (var t : TodoStore.get().listAll()) {
                if (Objects.equals(t.linkedReminderId, r.id)) {
                    t.linkedReminderId = null;
                    t.dueIso = null;
                    t.done   = true;
                    TodoStore.get().update(t);
                }
            }
        }
    }

    /** CUSTOMリマインダーからToDo自動生成 */
    public static synchronized void ensureTodoForReminder(Reminder r) {
        if (r == null) return;
        if (r.linkedTodoId != null) return;
        if (isArchivedCourseId(r.courseId)) return;

        boolean isAutoDeadline = r.autoGenerated
                              && r.priority == ReminderStore.Priority.WARNING_MED
                              && r.title != null
                              && r.title.contains("提出期限");

     // 期限日の自動警告
        if (isAutoDeadline) {
            TodoItem t = TodoStore.get().listAll().stream()
                .filter(x -> Objects.equals(x.courseId, r.courseId))
                .filter(x -> Objects.equals(x.nth,     r.nth))
                .filter(x -> Objects.equals(nullToEmpty(x.dueIso), nullToEmpty(r.dateIso)))
                .filter(x -> titleRoughEquals(x.title, "課題"))
                .findFirst()
                .orElseGet(() -> {
                    TodoItem nt = new TodoItem();
                    nt.courseId = r.courseId;
                    nt.nth      = r.nth;
                    nt.title    = "課題";
                    nt.dueIso   = r.dateIso;
                    return TodoStore.get().add(nt);
                });

            r.linkedTodoId = t.id;
            r.origin = "DEADLINE";
            ReminderStore.get().save();
            return;
        }


        // 上記以外
        var candidate = TodoStore.get().listAll().stream()
            .filter(t -> Objects.equals(t.courseId, r.courseId)
                      && Objects.equals(t.nth,     r.nth)
                      && Objects.equals(nullToEmpty(t.dueIso), nullToEmpty(r.dateIso))
                      && titleRoughEquals(t.title, r.title))
            .findFirst()
            .orElseGet(() -> {
                TodoItem nt = new TodoItem();
                nt.courseId = r.courseId; nt.nth = r.nth;
                nt.title = (r.title==null || r.title.isBlank()) ? "ToDo" : r.title;
                nt.detail = r.detail;
                nt.dueIso = r.dateIso;
                return TodoStore.get().add(nt);
            });

        candidate.linkedReminderId = r.id;
        TodoStore.get().update(candidate);
        r.linkedTodoId = candidate.id;
        r.origin = (r.origin==null? "CUSTOM" : r.origin);
        ReminderStore.get().save();
    }


    /** SavedFileIndex → ToDo/Reminderへ同期  */
    public static synchronized void syncFromFilesForDate(LocalDate date) {
        var list = SavedFileIndex.get().list().stream()
            .filter(e -> e.deadline != null && !e.deadline.isBlank() && Objects.equals(e.deadline, date.toString()))
            .filter(e -> "課題_未提出".equals(e.kind) || "課題_テキスト".equals(e.kind))
            .collect(Collectors.toList());

        for (var e : list) {
            // アーカイブ講義はスキップ
            if (isArchivedCourseId(e.courseId)) continue;

            var opt = TodoStore.get().listAll().stream()
            	    .filter(t -> Objects.equals(t.courseId, e.courseId))
            	    .filter(t -> Objects.equals(t.nth,     e.nth))
            	    .filter(t -> Objects.equals(nullToEmpty(t.dueIso), nullToEmpty(e.deadline)))
            	    .filter(t -> titleRoughEquals(t.title, "課題"))
            	    .findFirst();

            	TodoItem t = opt.orElseGet(() -> {
            	    TodoItem nt = new TodoItem();
            	    nt.courseId = e.courseId;
            	    nt.nth      = e.nth;
            	    nt.title    = "課題";
            	    nt.dueIso   = e.deadline;
            	    return TodoStore.get().add(nt);
            	});

            	if (e.path != null && !t.filePaths.contains(e.path)) t.filePaths.add(e.path);
            	TodoStore.get().update(t);

            	ensureLinkedReminder(t);
        }
    }

    /** 全体再同期 */
    public static synchronized void syncAllFromFiles() {
        var list = SavedFileIndex.get().list().stream()
            .filter(e -> e.deadline != null && !e.deadline.isBlank())
            .filter(e -> "課題_未提出".equals(e.kind) || "課題_テキスト".equals(e.kind))
            .toList();

        for (var e : list) {
            if (isArchivedCourseId(e.courseId)) continue;

            TodoItem t = TodoStore.get().listAll().stream()
                .filter(x -> Objects.equals(x.courseId, e.courseId))
                .filter(x -> Objects.equals(x.nth,     e.nth))
                .filter(x -> Objects.equals(nullToEmpty(x.dueIso), nullToEmpty(e.deadline)))
                .filter(x -> titleRoughEquals(x.title, "課題"))
                .findFirst()
                .orElseGet(() -> {
                    TodoItem nt = new TodoItem();
                    nt.courseId = e.courseId; nt.nth = e.nth; nt.title = "課題";
                    nt.dueIso   = e.deadline;
                    return TodoStore.get().add(nt);
                });

            if (e.path != null && !t.filePaths.contains(e.path)) t.filePaths.add(e.path);
            TodoStore.get().update(t);
            ensureLinkedReminder(t);
        }
    }

    public static synchronized void fullResync() {
        syncAllFromFiles();

        for (var t : TodoStore.get().listAll()) ensureLinkedReminder(t);

        for (var r : ReminderStore.get().listAll()) {
            if (isArchivedCourseId(r.courseId)) { ReminderStore.get().remove(r.id); continue; }
            onReminderEdited(r);
        }
    }


    // === ヘルパ ===

    /** ToDoに対応するリマインダーを保証 */
    private static void ensureLinkedReminder(TodoItem t) {
        if (isArchivedCourseId(t.courseId)) {
            if (t.linkedReminderId != null) {
                ReminderStore.get().remove(t.linkedReminderId);
                t.linkedReminderId = null;
                TodoStore.get().update(t);
            }
            return;
        }
        if (isDeadlineManaged(t)) {
            if (t.linkedReminderId != null) {
                ReminderStore.get().remove(t.linkedReminderId);
                t.linkedReminderId = null;
                TodoStore.get().update(t);
            }
            return;
        }
        if (t.done || t.dueIso == null || t.dueIso.isBlank()) {
            if (t.linkedReminderId != null) {
                ReminderStore.get().remove(t.linkedReminderId);
                t.linkedReminderId = null;
                TodoStore.get().update(t);
            }
            return;
        }

        Reminder r = null;
        if (t.linkedReminderId != null) r = ReminderStore.get().find(t.linkedReminderId);

        if (r == null) {
            r = new Reminder();
            r.priority = Priority.CUSTOM;
            r.autoGenerated = false;
            r.origin = "TODO";
        }

        r.dateIso  = t.dueIso;
        r.courseId = t.courseId;
        r.nth      = t.nth;
        r.title    = buildReminderTitleFromTodo(t);
        r.detail   = (t.detail==null? "" : t.detail);
        r.linkedTodoId = t.id;

        if (r.id == null) {
            ReminderStore.get().add(r);
        } else {
            ReminderStore.get().save();
        }

        if (!Objects.equals(t.linkedReminderId, r.id)) {
            t.linkedReminderId = r.id;
            TodoStore.get().update(t);
        }
    }

    private static boolean isArchivedCourseId(Integer courseId) {
        if (courseId == null) return false;

        var s = SettingsStore.load();
        if (s == null || s.workspaceDir == null || s.workspaceDir.isBlank()) return false;

        Course c = courseRepo.findAll().stream()
                .filter(x -> Objects.equals(x.id, courseId))
                .findFirst()
                .orElse(null);
        if (c == null) {
            return true;
        }

        try {
            Path ws = Path.of(s.workspaceDir);
            Path courseDir = ws.resolve(FileSaveOps.resolveCourseFolderName(c));
            return !Files.exists(courseDir);
        } catch (Exception ex) {
            return false;
        }
    }

    private static String buildReminderTitleFromTodo(TodoItem t) {
        return (t.title==null || t.title.isBlank()) ? "ToDo" : t.title;
    }
    private static String nullToEmpty(String s){ return s==null? "": s; }
    private static boolean titleRoughEquals(String a, String b) {
        return nullToEmpty(a).trim().equalsIgnoreCase(nullToEmpty(b).trim());
    }

    private static boolean isDeadlineManaged(TodoItem t) {
        if (t == null || t.dueIso == null || t.dueIso.isBlank()) return false;
        if (t.courseId == null || t.nth == null) return false;
        String due = t.dueIso;
        return SavedFileIndex.get().list().stream().anyMatch(e ->
            Objects.equals(e.courseId, t.courseId)
         && Objects.equals(e.nth,     t.nth)
         && Objects.equals(e.deadline, due)
         && e.kind != null && e.kind.startsWith("課題_")
        );
    }
    

}

